### PR TITLE
Install APCu stable version

### PR DESCRIPTION
**Pull request by dereckson**
APCu is now shipped on two channels, beta and stable.

The beta version is for PHP 7, the stable version PHP 5.3+.

### CODE REVIEW

**Comment by mikehaertl** [comment]
@dereckson Thanks for the hint and sorry for the long delay.
I won't create another 2.0.6 release though but wait for 2.0.7 instead.

**Comment by schmunk42** [comment]
I also ran into this with my images, they had beta+stable, but didn't they change it again?! I only remember being pretty confused.

Here are my versions:
- https://github.com/phundament/docker-images/blob/master/phundament/php-one/5.6-7.0/Dockerfile-5.6-fpm#L47
- https://github.com/phundament/docker-images/blob/master/phundament/php-one/5.6-7.0/Dockerfile-7.0-fpm#L48

_just FYI_

**Comment by dereckson** [comment]
Yes, they changed it again. Stable is now PHP 7.

**Comment by mikehaertl** [comment]
... so. Do we have to undo that change again?

**Comment by dereckson** [comment]
No, it would give APCu 5.1.0, which is the last beta version, and also for PHP 7.

The safest way seems to specify the last PHP 5 version explicitly, see #3.

**Pull request merged**
